backend:
  name: git-gateway
  branch: main
  local_backend: true

media_folder: static/images
public_folder: ../../static/images/

collections:
  - name: "travel-packages"
    preview: false
    label: "travel-packages"
    folder: "content/travel-location"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "title", name: "title",widget: "string"}
      - { label: "travel date" , name: "travel-date" ,widget: "string"}
      - { label: "image" , name: "feature-image" ,widget: "image"}
      - { label: "body" , name: "body" ,widget: "markdown"}

